# Generated by Django 3.2.3 on 2021-05-27 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.FloatField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(max_length=14)),
                ('iban', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercant', to=settings.AUTH_USER_MODEL, verbose_name='commerçant')),
            ],
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('commercant', models.ManyToManyField(to='app.Commercant')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cde', models.CharField(max_length=20, verbose_name='N° de commande')),
                ('date_cde', models.DateField(verbose_name='Date commande')),
                ('heure_cde', models.TimeField()),
                ('articles', models.ManyToManyField(to='app.Article')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('enseigne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enseigne')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='enseigne',
            field=models.ManyToManyField(to='app.Enseigne'),
        ),
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rue', models.CharField(max_length=250)),
                ('cp', models.CharField(max_length=10, verbose_name='Code postale')),
                ('ville', models.CharField(max_length=100)),
                ('etage', models.IntegerField(blank=True, null=True)),
                ('comp_adr', models.TextField(blank=True, null=True, verbose_name='Complément adresse')),
                ('tel', models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('enseigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.enseigne')),
            ],
        ),
    ]
